name: Build MyChildCore (net8.0 + 내장 DLL)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Restore dependencies
      run: dotnet restore MyChildCore.csproj

    - name: Build
      run: dotnet build MyChildCore.csproj -c Release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
       name: MyChildCore-DLL
       path: |
         .src/bin/Release/net8.0/*.dll
         .src/bin/Release/net8.0/*.pdb
         .src/bin/Release/net8.0/*.xml
       if-no-files-found: warn
