name: Build Stardew Valley Mod

on:
  push:
    paths:
      - '**.cs'
      - '**.csproj'
      - '.github/workflows/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet cache
      run: dotnet nuget locals all --clear

    - name: Build project
      run: dotnet build MyChildCore/MyChildCore.csproj -c Release
