name: Build MyChildCore (net48 + 내장 DLL)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET Framework Developer Pack
      uses: microsoft/setup-msbuild@v2

    - name: NuGet Restore
      run: nuget restore MyChildCore.csproj

    - name: Build
      run: dotnet build -c Release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
       name: MyChildCore-DLL
       path: |
         ./bin/Release/net48/*.dll
         ./bin/Release/net48/*.pdb
         ./bin/Release/net48/*.xml
       if-no-files-found: warn
