name: Build MyChildCore.Mod

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET Framework Developer Pack
      uses: microsoft/setup-msbuild@v2

    - name: NuGet Restore
      run: nuget restore MyChildCore.Mod/Mod.csproj

    - name: Build MyChildCore.Mod (net48)
      run: msbuild MyChildCore.Mod/Mod.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.8

    - name: List all DLLs in libs (for debug)
      run: Get-ChildItem MyChildCore.Mod/../libs | Select-Object Name, Length
      shell: pwsh

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyChildCore-Mod-DLL
        path: |
          MyChildCore.Mod/bin/Release/net48/*.dll

    - name: Post checkout source
      run: git --version
