name: Build MyChildCore (net8.0)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MyChildCore.csproj

    - name: Build
      run: dotnet build GenericModConfigMenu.csproj -c Release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyChildCore-DLL
        path: |
          ./bin/Release/net8.0/*.dll
          ./bin/Release/net8.0/*.pdb
        if-no-files-found: warn
