name: Build MyChildCore DLL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Prepare DLL dependencies
      run: |
        mkdir -p ~/.nuget/packages
        mkdir -p MyChildCore/lib
        cp -r DLL/* MyChildCore/lib/

    - name: Restore and Build
      run: |
        dotnet restore MyChildCore/MyChildCore.csproj
        dotnet build MyChildCore/MyChildCore.csproj -c Release --no-restore

    - name: Upload built DLL
      uses: actions/upload-artifact@v3
      with:
        name: MyChildCore-DLL
        path: |
          MyChildCore/bin/Release/net8.0/MyChildCore.dll
