name: .NET Framework Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.8.x'

    - name: Restore NuGet packages
      run: nuget restore MyChildCore.sln

    - name: Build solution
      run: msbuild MyChildCore.sln /p:Configuration=Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MyChildCore_Build
        path: |
          ./bin/Release/net48/*.dll
          ./bin/Release/net48/*.pdb
          ./bin/Release/net48/*.xml
