name: Build MyChildCore.Utilities

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Download SMAPI DLL
      run: |
        curl -L -o libs/StardewModdingAPI.dll https://github.com/Pathoschild/SMAPI/releases/download/4.0.0/StardewModdingAPI.dll
    
    - name: Setup .NET Framework Developer Pack
      uses: microsoft/setup-msbuild@v2

    - name: NuGet Restore
      run: |
        cd src
        nuget restore MyChildCore.csproj

    - name: Build MyChildCore.utilities (net48)
      run: |
        cd src
        msbuild MyChildCore.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.8
